### ISSUE TITLE
Cambiar el nombre de la tabla PresupuestoTip a Detalle de presupuesto

### ISSUE THREAD

**Issue by omarorlandini123** [omarorlandini123/Proy01#17]
Se debe cambiar el nombre de la tabla porque genera conflictos al entender el contenido

**Comment by jhoselynA** [comment]
se envió el pull reques

**Comment by omarorlandini123** [comment]
se recibió el pull request, tarea terminada

**Comment by omarorlandini123** [comment]
cierra la tarea
